---
geometry: left = 1.3cm, right = 1.3cm, top = 1.5cm, bottom = 1.5cm
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(readxl)
library(stringr)
library(dplyr)
library(tidyr)
library(tibble)
library(tidyverse)
library(kableExtra)
library(psych)
library(irr)
library(ggplot2)
library(data.table)
library(plyr)
library(lme4)
library(RColorBrewer)

options(digits = 4)
rm(list=ls())
```

```{r, include = FALSE}
completed_scores <- list.files(path = "../ti_scoring_data/Completed Scores", pattern = "KPMP TI Descriptor Scoring")
study_ids <- str_sub(completed_scores, 1, 8)
scorer_ids <- str_sub(completed_scores, 43, 43)
scorer_ids <- str_replace(scorer_ids, ".xlsx", "")

df <- data.frame()
for(i in 1:length(completed_scores)){
  
  data <- read_xlsx(paste0("../ti_scoring_data/Completed Scores/", completed_scores[i]), skip = 3, col_names = TRUE)
  data <- data[, 1:(grep("END", names(data))[1]-1)]

  data_scores <- data[c(1, 3:(nrow(data)-1)), ] 

  data_scores <- data_scores %>%
    filter(rowSums(is.na(data_scores)) != (ncol(data_scores) - 1))
  data_scores <- cbind(
    data.frame(Domain = c("", rep("Renal Tubular Atrophy", 3), 
                          rep("Tubular Cell Injury (other than atrophy)", 14), 
                          rep("Tubulitis", 2),
                          rep("Abnormal Tubular Luminal Morphology", 3),
                          rep("Intratubular Casts", 10),
                          rep("Tubular basement membrane Morphology", 2),
                          rep("Extracellular matrix", 2),
                          rep("Inflammation", 6))),
    data_scores)
  names(data_scores)[2] = "Descriptor"

  c_ix = which(data_scores[1,] == "Yes")
  data_scores = data_scores[-1, c(1:2, c_ix)]
  data_scores[, -c(1:2)] <- apply(data_scores[, -c(1:2)], 2, function(x) as.integer(x))
  
  domain_score <- aggregate(. ~ Domain, data_scores[,-2], function(x) ifelse(sum(x) >= 1, 1, 0))
  total_prst <- ifelse(apply(data_scores[,-c(1:2)], 2, sum) >= 1, 1, 0)

  data_scores$indiv_score <- rowMeans(data_scores[, -c(1:2)]) * 100
  domain_score$Score <- rowMeans(domain_score[, -1]) * 100
  total_score <- mean(total_prst) * 100
  dvst_score <- sum(data_scores$indiv_score > 0) # / nrow(data_scores) * 100
  
  tmp <- data.frame(
    
    scorer_id = scorer_ids[i],
    study_id = study_ids[i],
    
    ttl = total_score,
    
    dm_rta = domain_score[domain_score$Domain == "Renal Tubular Atrophy", "Score", drop = TRUE],
    dm_tci = domain_score[domain_score$Domain == "Tubular Cell Injury (other than atrophy)", "Score", drop = TRUE],
    dm_tblt = domain_score[domain_score$Domain == "Tubulitis", "Score", drop = TRUE],
    dm_atlm = domain_score[domain_score$Domain == "Abnormal Tubular Luminal Morphology", "Score", drop = TRUE],
    dm_ic = domain_score[domain_score$Domain == "Intratubular Casts", "Score", drop = TRUE],
    dm_tbmm = domain_score[domain_score$Domain == "Tubular basement membrane Morphology", "Score", drop = TRUE],
    dm_em = domain_score[domain_score$Domain == "Extracellular matrix", "Score", drop = TRUE],
    dm_inf = domain_score[domain_score$Domain == "Inflammation", "Score", drop = TRUE],
    
    idv_rta_classic = data_scores[data_scores$Descriptor == "Classic/Common-type", "indiv_score", drop = TRUE],
    idv_rta_thyroid = data_scores[data_scores$Descriptor == "Thyroidization-type", "indiv_score", drop = TRUE],
    idv_rta_endo = data_scores[data_scores$Descriptor == "Endocrine-type", "indiv_score", drop = TRUE],
    
    idv_tci_csimpl = data_scores[data_scores$Descriptor == "Cell Simplification", "indiv_score", drop = TRUE],
    idv_tci_cslough = data_scores[data_scores$Descriptor == "Cell Sloughing", "indiv_score", drop = TRUE],
    idv_tci_lossbb = data_scores[data_scores$Descriptor == "Loss of brush border", "indiv_score", drop = TRUE],
    idv_tci_cnecr = data_scores[data_scores$Descriptor == "Cell necrosis", "indiv_score", drop = TRUE],
    idv_tci_cappt = data_scores[data_scores$Descriptor == "Cell apoptosis", "indiv_score", drop = TRUE],
    idv_tci_cdtch = data_scores[data_scores$Descriptor == "Cell detachment", "indiv_score", drop = TRUE],
    idv_tci_tbmd = data_scores[data_scores$Descriptor == "TBM denudation", "indiv_score", drop = TRUE],
    idv_tci_cmit = data_scores[data_scores$Descriptor == "Cell Mitosis", "indiv_score", drop = TRUE],
    idv_tci_ccv = data_scores[data_scores$Descriptor == "Cell cytoplasmic vacuolization", "indiv_score", drop = TRUE],
    idv_tci_bac = data_scores[data_scores$Descriptor == "Blebbing of apical cytoplasm", "indiv_score", drop = TRUE],
    idv_tci_chd = data_scores[data_scores$Descriptor == "Cell hyaline droplets", "indiv_score", drop = TRUE],
    idv_tci_pd = data_scores[data_scores$Descriptor == "Pigmented droplets", "indiv_score", drop = TRUE],
    idv_tci_nh = data_scores[data_scores$Descriptor == "Nuclear Hyperchromasia", "indiv_score", drop = TRUE],
    idv_tci_vcc = data_scores[data_scores$Descriptor == "Viral cytopathic changes", "indiv_score", drop = TRUE],
    
    idv_tblt_lymph = data_scores[data_scores$Descriptor == "Lymphocytic", "indiv_score", drop = TRUE],
    idv_tblt_ntr = data_scores[data_scores$Descriptor == "Neutrophilic", "indiv_score", drop = TRUE],
    
    idv_atlm_ld = data_scores[data_scores$Descriptor == "Luminal dilation", "indiv_score", drop = TRUE],
    idv_atlm_mcc = data_scores[data_scores$Descriptor == "Microcystic change", "indiv_score", drop = TRUE],
    idv_atlm_tc = data_scores[data_scores$Descriptor == "Tubular cysts", "indiv_score", drop = TRUE],
    
    idv_ic_rbc = data_scores[data_scores$Descriptor == "RBCs", "indiv_score", drop = TRUE],
    idv_ic_cec = data_scores[data_scores$Descriptor == "(Cellular) Erythrocyte casts", "indiv_score", drop = TRUE],
    idv_ic_clc = data_scores[data_scores$Descriptor == "(Cellular) Leukocyte casts", "indiv_score", drop = TRUE],
    idv_ic_cecc = data_scores[data_scores$Descriptor == "(Cellular) Epithelial cell casts", "indiv_score", drop = TRUE],
    idv_ic_athc = data_scores[data_scores$Descriptor == "(Acellular) Tamm-Horsfall casts", "indiv_score", drop = TRUE],
    idv_ic_ahc = data_scores[data_scores$Descriptor == "(Acellular) Hyaline casts", "indiv_score", drop = TRUE],
    idv_ic_acc = data_scores[data_scores$Descriptor == "Acellular casts crystals", "indiv_score", drop = TRUE],
    idv_ic_pc = data_scores[data_scores$Descriptor == "(Acellular) Pigmented casts", "indiv_score", drop = TRUE],
    idv_ic_lcc = data_scores[data_scores$Descriptor == "(Acellular) Light-chain casts", "indiv_score", drop = TRUE],
    idv_ic_ric = data_scores[data_scores$Descriptor == "Renal intratubular casts [NOS]", "indiv_score", drop = TRUE],
    
    idv_tbmm_tbmr = data_scores[data_scores$Descriptor == "Tubular Basement membrane rupture", "indiv_score", drop = TRUE],
    idv_tbmm_tbml = data_scores[data_scores$Descriptor == "Tubular basement membrane lamellation", "indiv_score", drop = TRUE],
    
    idv_em_if = data_scores[data_scores$Descriptor == "Interstitial fibrosis", "indiv_score", drop = TRUE],
    idv_em_ie = data_scores[data_scores$Descriptor == "Interstitial edema", "indiv_score", drop = TRUE],
    
    idv_inf_lymp = data_scores[data_scores$Descriptor == "Lymphocytes", "indiv_score", drop = TRUE],
    idv_inf_plasma = data_scores[data_scores$Descriptor == "Plasma cells", "indiv_score", drop = TRUE],
    idv_inf_eosin = data_scores[data_scores$Descriptor == "Eosinophils", "indiv_score", drop = TRUE],
    idv_inf_neutr = data_scores[data_scores$Descriptor == "Neutrophils", "indiv_score", drop = TRUE],
    idv_inf_granul = data_scores[data_scores$Descriptor == "Granulomas", "indiv_score", drop = TRUE],
    idv_inf_fc = data_scores[data_scores$Descriptor == "Foam cells", "indiv_score", drop = TRUE],
    
    dvst = dvst_score
      )
  
  df <- rbind(df, tmp)
  
}

idv <- df[, c(1:2, grep("^idv_", names(df)))]
idv_prst <- aggregate(. ~ study_id, idv[,-1], function(x) ifelse(sum(x) >= 1, 1, 0))
idv_prst <- apply(idv_prst[, -1], 2, function(x) sum(x>0))  
idv_prst <- data.frame(
  Descriptor = data_scores$Descriptor, 
  n_smp_prst = idv_prst 
  )

idv_prst$Descriptor <- factor(idv_prst$Descriptor, levels= idv_prst$Descriptor)

prb_idv <- idv_prst %>% filter(n_smp_prst == 0)
```

```{r}
df_score <- data.frame()

for(i in 3:54){

  score <- df[, c(1:2, i)]
  score_df <- spread(score, key = scorer_id, value = names(score)[3])
  
  rownames(score_df) <- paste0(names(score)[3], score_df$study_id)
  tmp <- score_df[, -1]
  
  df_score <- rbind(df_score, tmp)
  
}
```

```{r, include=FALSE}
df <- df %>%
  add_column(dvst = df$dvst, .before = "ttl")

df_icc_lme <- data.frame()

for(i in 3:54){

  score <- df[, c(1:2, i)]
  score_df <- spread(score, key = scorer_id, value = names(score)[3])
  
  rownames(score_df) <- score_df$study_id
  score_df <- score_df[, -1]
  
  score_rst <- ICC(score_df, missing = FALSE, alpha = .05)$results
  score_icc <- score_rst[score_rst$type == "ICC2", "ICC"]
  score_lb <- score_rst[score_rst$type == "ICC2", "lower bound"]
  score_ub <- score_rst[score_rst$type == "ICC2", "upper bound"]
  
  
  tmp <- data.frame(
    
    score_name = names(score)[3],
    icc = score_icc,
    icc_lb = score_lb,
    icc_ub = score_ub
    
  )
  
  df_icc_lme <- rbind(df_icc_lme, tmp)
  
}

df_icc_lme <- df_icc_lme %>%
  add_column(Score = c("Descriptor Diversity Score",
                       "Total Pathology Score",
                       unique(data_scores$Domain),
                       unique(data_scores$Descriptor)), .after = "score_name")

df_icc_lme$Score <- factor(df_icc_lme$Score, levels = df_icc_lme$Score)

na_icc <- df_icc_lme %>% filter(is.na(icc))
df_icc_lme[is.na(df_icc_lme)] <- 0 

df_icc_idv <- df_icc_lme[11:52,]
df_icc_idv$Domain <- factor(data_scores$Domain, levels=unique(data_scores$Domain))

df_icc_idv1 <- df_icc_idv[1:22,]
df_icc_idv2 <- df_icc_idv[23:42,]
df_icc_others <- df_icc_lme[1:10,]
```

```{r, fig.align='center', fig.cap='Estimated ICC of individual descriptor scores with 95\\% CI. Marked NA when the features were never present in any of 9 samples. (Part 1)', fig.height=6.4, out.width='90%'}
colors = brewer.pal(n=8, name="Dark2")

ggplot(df_icc_idv1, aes(x = Score, y = icc, fill = Domain)) + 
  geom_bar(stat = "identity") + coord_flip() + theme_bw() +
  scale_y_continuous(name = "ICC", breaks = c(0, 0.25, 0.5, 0.75, 0.9)) + scale_x_discrete(name = "Score") +
  scale_fill_manual(values = colors[1:4]) +
  theme(axis.title.x = element_text(size = 10), axis.title.y = element_text(size = 10), legend.position = "none") +
  geom_vline(xintercept = c(3.5, 17.5, 19.5), color = "black", linetype = 3, size = 1) +
  # annotate("text", x = 2, y = 0.845, label = "Renal Tubular Atrophy", size = 3, color = "blue") +
  # annotate("text", x = 10.5, y = 0.73, label = "Tubular Cell Injury (other than atrophy)", size = 3, color = "blue") +
  # annotate("text", x = 18.5, y = 0.94, label = "Tubulitis", size = 3, color = "blue") +
  geom_hline(yintercept = c(0.5, 0.75, 0.9), linetype = 2, color = "red") +
  annotate("text", x = c(17, 19), y = -0.05, label = "NA", size = 3) +
  geom_errorbar(aes(ymin=icc_lb, ymax=icc_ub),
                  width=.2,                    # Width of the error bars
                  position=position_dodge(.9))
```

```{r, fig.align='center', fig.cap='Estimated ICC of individual descriptor scores with 95\\% CI. Marked NA when the features were never present in any of 9 samples. (Part 2)', fig.height=6, out.width='98%'}
ggplot(df_icc_idv2, aes(x = Score, y = icc, fill = Domain)) + 
  geom_bar(stat = "identity") + coord_flip() + theme_bw() +
  scale_y_continuous(name = "ICC", breaks = c(0, 0.25, 0.5, 0.75, 0.9)) + scale_x_discrete(name = "Score") +
  scale_fill_manual(values = colors[5:8]) +
  theme(axis.title.x = element_text(size = 10), axis.title.y = element_text(size = 10), legend.position = "none") +
  geom_vline(xintercept = c(10.5, 12.5, 14.5), color = "black", linetype = 3, size = 1) +
  # annotate("text", x = 2, y = 0.65, label = "Abnormal Tubular Luminal Morphology", size = 3, color = "blue") +
  # annotate("text", x = 8, y = 0.81, label = "Intratubular Casts", size = 3, color = "blue") +
  # annotate("text", x = 14.3, y = 0.63, label = "Tubular Basement Membrane Morphology", size = 3, color = "blue") +
  # annotate("text", x = 16.5, y = 0.8, label = "Extracellular Matrix", size = 3, color = "blue") +
  # annotate("text", x = 20.5, y = 0.85, label = "Inflammation", size = 3, color = "blue") +
  geom_hline(yintercept = c(0.5, 0.75, 0.9), linetype = 2, color = "red") +
  annotate("text", x = c(2, 9, 19, 20), y = -0.05, label = "NA", size = 3) +
  geom_errorbar(aes(ymin=icc_lb, ymax=icc_ub),
                  width=.2,                    # Width of the error bars
                  position=position_dodge(.9))
```

```{r, fig.align='center', fig.cap='Estimated ICC of individual descriptor scores with 95\\% CI. Marked NA when the features were never present in any of 9 samples. Dotted blue lines separate descriptors into 8 domains: Renal Tubular Atrophy, Tubular Cell Injury (other than atrophy), Tubulitis, Abnormal Tubular Luminal Morphology, Intratubular Casts, Tubular basement membrane Morphology, Extracellular matrix, Inflammation (from the bottom)', fig.height=10, out.width='95%'}
ggplot(df_icc_idv, aes(x = Score, y = icc, fill = Domain)) + 
  geom_bar(stat = "identity") + coord_flip() + theme_bw() +
  scale_fill_manual(values = colors[1:8]) +
  scale_y_continuous(name = "ICC", breaks = c(0, 0.25, 0.5, 0.75, 0.9)) + scale_x_discrete(name = "Score") +
  theme(axis.title.x = element_text(size = 10), axis.title.y = element_text(size = 10), legend.position = "none") +
  geom_vline(xintercept = c(3.5, 17.5, 19.5, 22.5, 32.5, 34.5, 36.5), color = "black", linetype = 3, size = 1) +
  geom_hline(yintercept = c(0.5, 0.75, 0.9), linetype = 2, color = "red") +
  annotate("text", x = c(17, 19, 24, 31, 41, 42), y = -0.05, label = "NA", size = 3) +
  geom_errorbar(aes(ymin=icc_lb, ymax=icc_ub),
                  width=.2,                    # Width of the error bars
                  position=position_dodge(.9))
```

\clearpage 

```{r, fig.align='center', fig.cap='Estimated ICC of total pathology, domain specific, and descriptor diversity scores with 95\\% CI.', fig.height=5, out.width='95%'}
ggplot(df_icc_others, aes(x = Score, y = icc)) + 
  geom_bar(stat = "identity", fill = c("gray", "gray",colors)) + coord_flip() + theme_bw() +
  scale_y_continuous(name = "ICC", breaks = c(0, 0.25, 0.5, 0.75, 0.9)) +
scale_x_discrete(name = "Score") +
  theme(axis.title.x = element_text(size = 10), axis.title.y = element_text(size = 10)) +
  geom_vline(xintercept = c(1.5, 2.5), color = "black", linetype = 3, size = 1) +
  geom_hline(yintercept = c(0.5, 0.75, 0.9), linetype = 2, color = "red") +
  geom_errorbar(aes(ymin=icc_lb, ymax=icc_ub),
                  width=.2,                    # Width of the error bars
                  position=position_dodge(.9))
```

```{r echo=FALSE, out.width='95%', fig.cap = "Domain specific score - Renal Tubular Atrophy (\\%)", fig.align='center', fig.height = 4}
dm_rta <- df[, c("scorer_id", "study_id", "dm_rta")]
dm_rta$study_id <- factor(dm_rta$study_id, levels = c("27-10089", "30-11033", "31-10063",
                                                  "29-10012", "30-10125", "32-10296", 
                                                  "28-10051", "29-10395", "34-10184"), labels = c("Sample 1","Sample 2","Sample 3",
                                                                                                  "Sample 4","Sample 5","Sample 6",
                                                                                                  "Sample 7","Sample 8","Sample 9"))
dm_rta_df <- spread(dm_rta, key = scorer_id, value = dm_rta)

rownames(dm_rta_df) <- dm_rta_df$study_id
dm_rta_df <- dm_rta_df[, -1]

dm_rta$study_id <- fct_rev(dm_rta$study_id)
ggplot(dm_rta, aes(x = study_id, y = dm_rta, color = scorer_id)) +
  geom_jitter(size = 2.5, height = 3, width = 0, alpha = 0.8) + coord_flip() +  
  theme_bw() + labs(color = "Scorer") + ylab("Domain specific score (%) - Renal Tubular Atrophy") +
  geom_vline(xintercept = c(3.5, 6.5)) +
  # geom_vline(xintercept = c(1.5, 2.5, 4.5, 5.5, 7.5, 8.5), linetype = 3) +
  theme(axis.title.y = element_blank())
```

```{r echo=FALSE, out.width='95%', fig.cap = "Domain specific score - Tubular Cell Injury (other than atrophy) (\\%)", fig.align='center', fig.height = 4}
dm_tci <- df[, c("scorer_id", "study_id", "dm_tci")]
dm_tci$study_id <- factor(dm_tci$study_id, levels = c("27-10089", "30-11033", "31-10063",
                                                  "29-10012", "30-10125", "32-10296", 
                                                  "28-10051", "29-10395", "34-10184"))
dm_tci_df <- spread(dm_tci, key = scorer_id, value = dm_tci)

rownames(dm_tci_df) <- dm_tci_df$study_id
dm_tci_df <- dm_tci_df[, -1]

dm_tci$study_id <- fct_rev(dm_tci$study_id)
ggplot(dm_tci, aes(x = study_id, y = dm_tci, color = scorer_id)) +
  geom_jitter(size = 2, width = 0.3, height = 1) + coord_flip() +  
  theme_bw() + xlab("Sample") + labs(color = "Scorer") +
  geom_vline(xintercept = c(3.5, 6.5)) +
  geom_vline(xintercept = c(1.5, 2.5, 4.5, 5.5, 7.5, 8.5), linetype = 3) +
  theme(axis.title.x = element_blank())
```


```{r echo=FALSE, out.width='95%', fig.cap = "Domain specific score - Tubulitis (\\%)", fig.align='center', fig.height = 4}
dm_tblt <- df[, c("scorer_id", "study_id", "dm_tblt")]
dm_tblt$study_id <- factor(dm_tblt$study_id, levels = c("27-10089", "30-11033", "31-10063",
                                                  "29-10012", "30-10125", "32-10296", 
                                                  "28-10051", "29-10395", "34-10184"))
dm_tblt_df <- spread(dm_tblt, key = scorer_id, value = dm_tblt)

rownames(dm_tblt_df) <- dm_tblt_df$study_id
dm_tblt_df <- dm_tblt_df[, -1]

dm_tblt$study_id <- fct_rev(dm_tblt$study_id)
ggplot(dm_tblt, aes(x = study_id, y = dm_tblt, color = scorer_id)) +
  geom_jitter(size = 2, width = 0.3, height = 1) + coord_flip() +  
  theme_bw() + xlab("Sample") + labs(color = "Scorer") +
  geom_vline(xintercept = c(3.5, 6.5)) +
  geom_vline(xintercept = c(1.5, 2.5, 4.5, 5.5, 7.5, 8.5), linetype = 3) +
  theme(axis.title.x = element_blank())
```

```{r echo=FALSE, out.width='95%', fig.cap = "Domain specific score - Abnormal Tubular Luminal Morphology (\\%)", fig.align='center', fig.height = 4}
dm_atlm <- df[, c("scorer_id", "study_id", "dm_atlm")]
dm_atlm$study_id <- factor(dm_atlm$study_id, levels = c("27-10089", "30-11033", "31-10063",
                                                  "29-10012", "30-10125", "32-10296", 
                                                  "28-10051", "29-10395", "34-10184"), labels = c("Sample 1","Sample 2","Sample 3",
                                                                                                  "Sample 4","Sample 5","Sample 6",
                                                                                                  "Sample 7","Sample 8","Sample 9"))
dm_atlm_df <- spread(dm_atlm, key = scorer_id, value = dm_atlm)

rownames(dm_atlm_df) <- dm_atlm_df$study_id
dm_atlm_df <- dm_atlm_df[, -1]

dm_atlm$study_id <- fct_rev(dm_atlm$study_id)
ggplot(dm_atlm, aes(x = study_id, y = dm_atlm, color = scorer_id)) +
  geom_jitter(size = 2.5, width = 0, height = 3, alpha = 0.8) + coord_flip() +  
  theme_bw() + xlab("Sample") + labs(color = "Scorer") + ylab("Domain specific score (%) - Abnormal Tubular Luminal Morphology") +
  geom_vline(xintercept = c(3.5, 6.5)) +
  # geom_vline(xintercept = c(1.5, 2.5, 4.5, 5.5, 7.5, 8.5), linetype = 3) +
  theme(axis.title.y = element_blank())
```

```{r echo=FALSE, out.width='95%', fig.cap = "Domain specific score - Intratubular Casts (\\%)", fig.align='center', fig.height = 4}
dm_ic <- df[, c("scorer_id", "study_id", "dm_ic")]
dm_ic$study_id <- factor(dm_ic$study_id, levels = c("27-10089", "30-11033", "31-10063",
                                                  "29-10012", "30-10125", "32-10296", 
                                                  "28-10051", "29-10395", "34-10184"))
dm_ic_df <- spread(dm_ic, key = scorer_id, value = dm_ic)

rownames(dm_ic_df) <- dm_ic_df$study_id
dm_ic_df <- dm_ic_df[, -1]

dm_ic$study_id <- fct_rev(dm_ic$study_id)
ggplot(dm_ic, aes(x = study_id, y = dm_ic, color = scorer_id)) +
  geom_jitter(size = 2, width = 0.3, height = 1) + coord_flip() +  
  theme_bw() + xlab("Sample") + labs(color = "Scorer") +
  geom_vline(xintercept = c(3.5, 6.5)) +
  geom_vline(xintercept = c(1.5, 2.5, 4.5, 5.5, 7.5, 8.5), linetype = 3) +
  theme(axis.title.x = element_blank())
```

```{r echo=FALSE, out.width='95%', fig.cap = "Domain specific score - Tubular Basement Membrane Morphology (\\%)", fig.align='center', fig.height = 4}
dm_tbmm <- df[, c("scorer_id", "study_id", "dm_tbmm")]
dm_tbmm$study_id <- factor(dm_tbmm$study_id, levels = c("27-10089", "30-11033", "31-10063",
                                                  "29-10012", "30-10125", "32-10296", 
                                                  "28-10051", "29-10395", "34-10184"))
dm_tbmm_df <- spread(dm_tbmm, key = scorer_id, value = dm_tbmm)

rownames(dm_tbmm_df) <- dm_tbmm_df$study_id
dm_tbmm_df <- dm_tbmm_df[, -1]

dm_tbmm$study_id <- fct_rev(dm_tbmm$study_id)
ggplot(dm_tbmm, aes(x = study_id, y = dm_tbmm, color = scorer_id)) +
  geom_jitter(size = 2.5, width = 0.3, height = 1) + coord_flip() +  
  theme_bw() + xlab("Sample") + labs(color = "Scorer") +
  geom_vline(xintercept = c(3.5, 6.5)) +
  geom_vline(xintercept = c(1.5, 2.5, 4.5, 5.5, 7.5, 8.5), linetype = 3) +
  theme(axis.title.x = element_blank())
```

```{r echo=FALSE, out.width='95%', fig.cap = "Domain specific score - Extracellular matrix (\\%)", fig.align='center', fig.height = 4}
dm_em <- df[, c("scorer_id", "study_id", "dm_em")]
dm_em$study_id <- factor(dm_em$study_id, levels = c("27-10089", "30-11033", "31-10063",
                                                  "29-10012", "30-10125", "32-10296", 
                                                  "28-10051", "29-10395", "34-10184"))
dm_em_df <- spread(dm_em, key = scorer_id, value = dm_em)

rownames(dm_em_df) <- dm_em_df$study_id
dm_em_df <- dm_em_df[, -1]

dm_em$study_id <- fct_rev(dm_em$study_id)
ggplot(dm_em, aes(x = study_id, y = dm_em, color = scorer_id)) +
  geom_jitter(size = 2, width = 0.3, height = 1) + coord_flip() +  
  theme_bw() + xlab("Sample") + labs(color = "Scorer") +
  geom_vline(xintercept = c(3.5, 6.5)) +
  geom_vline(xintercept = c(1.5, 2.5, 4.5, 5.5, 7.5, 8.5), linetype = 3) +
  theme(axis.title.x = element_blank())
```

```{r echo=FALSE, out.width='95%', fig.cap = "Domain specific score - Inflammation (\\%)", fig.align='center', fig.height = 4}
dm_inf <- df[, c("scorer_id", "study_id", "dm_inf")]
dm_inf$study_id <- factor(dm_inf$study_id, levels = c("27-10089", "30-11033", "31-10063",
                                                  "29-10012", "30-10125", "32-10296", 
                                                  "28-10051", "29-10395", "34-10184"))
dm_inf_df <- spread(dm_inf, key = scorer_id, value = dm_inf)

rownames(dm_inf_df) <- dm_inf_df$study_id
dm_inf_df <- dm_inf_df[, -1]

dm_inf$study_id <- fct_rev(dm_inf$study_id)
ggplot(dm_inf, aes(x = study_id, y = dm_inf, color = scorer_id)) +
  geom_jitter(size = 2, width = 0.3, height = 1) + coord_flip() +  
  theme_bw() + xlab("Sample") + labs(color = "Scorer") +
  geom_vline(xintercept = c(3.5, 6.5)) +
  geom_vline(xintercept = c(1.5, 2.5, 4.5, 5.5, 7.5, 8.5), linetype = 3) +
  theme(axis.title.x = element_blank())
```

```{r echo=FALSE, out.width='95%', fig.cap = "Descriptor Diversity Score (0-42)", fig.align='center', fig.height = 4}
dvst <- df[, c("scorer_id", "study_id", "dvst")]

dvst <- dvst %>%
  mutate(n_dvst = dvst * 42 / 100)

dvst$study_id <- factor(dvst$study_id, levels = c("27-10089", "30-11033", "31-10063",
                                                  "29-10012", "30-10125", "32-10296", 
                                                  "28-10051", "29-10395", "34-10184"))
dvst_df <- spread(dvst %>% select(-dvst), key = scorer_id, value = n_dvst)

rownames(dvst_df) <- dvst_df$study_id
dvst_df <- dvst_df[, -1]

dvst$study_id <- fct_rev(dvst$study_id)
ggplot(dvst, aes(x = study_id, y = dvst, color = scorer_id)) +
  geom_jitter(size = 2, width = 0.3, height = 1) + coord_flip() +  
  theme_bw() + xlab("Sample") + labs(color = "Scorer") +
  geom_vline(xintercept = c(3.5, 6.5)) +
  geom_vline(xintercept = c(1.5, 2.5, 4.5, 5.5, 7.5, 8.5), linetype = 3) +
  theme(axis.title.x = element_blank())
```

```{r echo=FALSE, out.width='95%', fig.cap = "Total Pathology Score (\\%)", fig.align='center', fig.height = 4}
ttl <- df[, c("scorer_id", "study_id", "ttl")]
ttl$study_id <- factor(ttl$study_id, levels = c("27-10089", "30-11033", "31-10063",
                                                  "29-10012", "30-10125", "32-10296", 
                                                  "28-10051", "29-10395", "34-10184"))
ttl_df <- spread(ttl, key = scorer_id, value = ttl)

rownames(ttl_df) <- ttl_df$study_id
ttl_df <- ttl_df[, -1]

ttl$study_id <- fct_rev(ttl$study_id)
ggplot(ttl, aes(x = study_id, y = ttl, color = scorer_id)) +
  geom_jitter(size = 2, width = 0.3, height = 1) + coord_flip() +  
  theme_bw() + xlab("Sample") + labs(color = "Scorer") +
  geom_vline(xintercept = c(3.5, 6.5)) +
  geom_vline(xintercept = c(1.5, 2.5, 4.5, 5.5, 7.5, 8.5), linetype = 3) +
  theme(axis.title.x = element_blank())
```

```{r, include = FALSE}
completed_scores <- list.files(path = "../ti_scoring_data/Completed Scores", pattern = "KPMP TI Descriptor Scoring")
study_ids <- str_sub(completed_scores, 1, 8)
scorer_ids <- str_sub(completed_scores, 43, 43)
scorer_ids <- str_replace(scorer_ids, ".xlsx", "")

tmp <- data.frame(
  file_id = completed_scores,
  study_id = study_ids,
  scorer_id = scorer_ids
)

df_grid = data.frame()

for (i in 1:nrow(tmp)){
  
  data <- read_xlsx(paste0("../ti_scoring_data/Completed Scores/", completed_scores[i]), skip = 3, col_names = TRUE)
  data <- data[, 1:(grep("END", names(data))[1]-1)]

  data_scores <- data[c(1, 3:(nrow(data)-1)), ] 

  data_scores <- data_scores %>%
    filter(rowSums(is.na(data_scores)) != (ncol(data_scores) - 1))
  data_scores[-1 , which(data_scores[1, ] == "No")] = NA
  
  n_grid = ncol(data_scores[, -1])
  grid = paste0(study_ids[i], "_", "G", 1:n_grid)
  
  tmp_grid = data.frame(
    
    sample = rep(study_ids[i], n_grid),
    grid = grid,
    pathologist = rep(scorer_ids[i], n_grid),
    rta_classic = as.integer(data_scores[2, -1]),
    rta_thyroid = as.integer(data_scores[3, -1]),
    rta_endo = as.integer(data_scores[4, -1]),
    tci_csimpl = as.integer(data_scores[5, -1]),
    tci_cslough = as.integer(data_scores[6, -1]),
    tci_lossbb = as.integer(data_scores[7, -1]),
    tci_cnecr = as.integer(data_scores[8, -1]),
    tci_cappt = as.integer(data_scores[9, -1]),
    tci_cdtch = as.integer(data_scores[10, -1]),
    tci_tbmd = as.integer(data_scores[11, -1]),
    tci_cmit = as.integer(data_scores[12, -1]),
    tci_ccv = as.integer(data_scores[13, -1]),
    tci_bac = as.integer(data_scores[14, -1]),
    tci_chd = as.integer(data_scores[15, -1]),
    tci_pd = as.integer(data_scores[16, -1]),
    tci_nh = as.integer(data_scores[17, -1]),
    tci_vcc = as.integer(data_scores[18, -1]),
    tblt_lymph = as.integer(data_scores[19, -1]),
    tblt_ntr = as.integer(data_scores[20, -1]),
    atlm_ld = as.integer(data_scores[21, -1]),
    atlm_mcc = as.integer(data_scores[22, -1]),
    atlm_tc = as.integer(data_scores[23, -1]),
    ic_rbc = as.integer(data_scores[24, -1]),
    ic_cec = as.integer(data_scores[25, -1]),
    ic_clc = as.integer(data_scores[26, -1]),
    ic_cecc = as.integer(data_scores[27, -1]),
    ic_athc = as.integer(data_scores[28, -1]),
    ic_ahc = as.integer(data_scores[29, -1]),
    ic_acc = as.integer(data_scores[30, -1]),
    ic_pc = as.integer(data_scores[31, -1]),
    ic_lcc = as.integer(data_scores[32, -1]),
    ic_ric = as.integer(data_scores[33, -1]),
    tbmm_tbmr = as.integer(data_scores[34, -1]),
    tbmm_tbml = as.integer(data_scores[35, -1]),
    em_if = as.integer(data_scores[36, -1]),
    em_ie = as.integer(data_scores[37, -1]),
    inf_lymp = as.integer(data_scores[38, -1]),
    inf_plasma = as.integer(data_scores[39, -1]),
    inf_eosin = as.integer(data_scores[40, -1]),
    inf_neutr = as.integer(data_scores[41, -1]),
    inf_granul = as.integer(data_scores[42, -1]),
    inf_fc = as.integer(data_scores[43, -1])
  )
  
  df_grid = rbind(df_grid, tmp_grid)
  
}

lme_grid = lmer(rta_classic ~ 1 + (1|sample) + (1|grid), data = df_grid[, 1:4], na.action = na.omit)
```

```{r, include = FALSE}
completed_scores <- list.files(path = "../ti_scoring_data/Completed Scores", pattern = "KPMP TI Descriptor Scoring")
study_ids <- str_sub(completed_scores, 1, 8)
scorer_ids <- str_sub(completed_scores, 43, 43)
scorer_ids <- str_replace(scorer_ids, ".xlsx", "")

tmp <- data.frame(
  file_id = completed_scores,
  study_id = study_ids,
  scorer_id = scorer_ids
)

tmp_A = tmp %>% filter(scorer_id %in% c("A","B","C","D","E"))

samples_A = unique(tmp_A$study_id)
n_samples_A = length(samples_A)
# samples_A = tmp %>% filter(scorer_id %in% c("A","B","C","D","E"))
# samples_F = tmp %>% filter(scorer_id %in% c("F","H","I"))
# samples_K = tmp %>% filter(scorer_id %in% c("K","L","M","N"))

scorers_A = unique(tmp_A$scorer_id)
n_scorers_A = length(scorers_A)

#cmpt_A <- setNames(data.frame(matrix(ncol = n_scorers, nrow = 0)), scorers)
cmpt_A <- data.frame()
grid_3011033 <- read_xlsx("../ti_scoring_data/Completed Scores/30-11033_KPMP TI Descriptor Scoring_ScorerA.xlsx", skip = 3, col_names = TRUE)
grid_3011033 <- grid_3011033[, 1:(grep("END", names(grid_3011033))[1]-1)]
grid_3011033 <- names(grid_3011033[2, -1])

for(i in 1:n_samples_A){
  
  files = tmp_A[tmp_A$study_id == samples_A[i],]
  n_files = nrow(files)

  df_cmpt <- data.frame()
  
  for(j in 1:n_files){
    data <- read_xlsx(paste0("../ti_scoring_data/Completed Scores/", files$file[j]), skip = 3, col_names = TRUE)
    data <- data[, 1:(grep("END", names(data))[1]-1)]
    data_cmpt <- data[2, -1]
    rownames(data_cmpt) = files$scorer_id[j]
    if(files$study_id == "30-11033"){
      colnames(data_cmpt) = paste0(files$study_id[j], "_", grid_3011033)
    } else{
      colnames(data_cmpt) = paste0(files$study_id[j], "_", colnames(data_cmpt))
    }
    
    df_cmpt <- rbind(df_cmpt, data_cmpt)
  }
  
  tdf_cmpt <- transpose(df_cmpt)
  rownames(tdf_cmpt) <- colnames(df_cmpt)
  colnames(tdf_cmpt) <- rownames(df_cmpt)
  
  cmpt_A <- rbind(cmpt_A, tdf_cmpt)
}

tmp_F = tmp %>% filter(scorer_id %in% c("F","H","I"))

samples_F = unique(tmp_F$study_id)
n_samples_F = length(samples_F)
# samples_K = tmp %>% filter(scorer_id %in% c("K","L","M","N"))

scorers_F = unique(tmp_F$scorer_id)
n_scorers_F = length(scorers_F)

cmpt_F <- data.frame()
for(i in 1:n_samples_F){
  
  files = tmp_F[tmp_F$study_id == samples_F[i],]
  n_files = nrow(files)

  df_cmpt <- data.frame()
  
  for(j in 1:n_files){
    data <- read_xlsx(paste0("../ti_scoring_data/Completed Scores/", files$file[j]), skip = 3, col_names = TRUE)
    data <- data[, 1:(grep("END", names(data))[1]-1)]
    data_cmpt <- data[2, -1]
    rownames(data_cmpt) = files$scorer_id[j]
    colnames(data_cmpt) = paste0(files$study_id[j], "_", colnames(data_cmpt))
    
    df_cmpt <- rbind(df_cmpt, data_cmpt)
  }
  
  tdf_cmpt <- transpose(df_cmpt)
  rownames(tdf_cmpt) <- colnames(df_cmpt)
  colnames(tdf_cmpt) <- rownames(df_cmpt)
  
  cmpt_F <- rbind(cmpt_F, tdf_cmpt)
}


tmp_K = tmp %>% filter(scorer_id %in% c("K","L","M","N"))

samples_K = unique(tmp_K$study_id)
n_samples_K = length(samples_K)

scorers_K = unique(tmp_K$scorer_id)
n_scorers_K = length(scorers_K)

cmpt_K <- data.frame()
for(i in 1:n_samples_K){
  
  files = tmp_K[tmp_K$study_id == samples_K[i],]
  n_Kiles = nrow(files)

  df_cmpt <- data.frame()
  
  for(j in 1:n_Kiles){
    data <- read_xlsx(paste0("../ti_scoring_data/Completed Scores/", files$file[j]), skip = 3, col_names = TRUE)
    data <- data[, 1:(grep("END", names(data))[1]-1)]
    data_cmpt <- data[2, -1]
    rownames(data_cmpt) = files$scorer_id[j]
    colnames(data_cmpt) = paste0(files$study_id[j], "_", colnames(data_cmpt))
    
    df_cmpt <- rbind(df_cmpt, data_cmpt)
  }
  
  tdf_cmpt <- transpose(df_cmpt)
  rownames(tdf_cmpt) <- colnames(df_cmpt)
  colnames(tdf_cmpt) <- rownames(df_cmpt)
  
  cmpt_K <- rbind(cmpt_K, tdf_cmpt)
}

cmpt_A_tmp <- setNames(data.frame(matrix(ncol = n_scorers_F + n_scorers_K, nrow = nrow(cmpt_A))), c(scorers_F, scorers_K))
rownames(cmpt_A_tmp) <- rownames(cmpt_A)

cmpt_A_tmp <- cbind(cmpt_A, cmpt_A_tmp)

cmpt_F_tmp <- setNames(data.frame(matrix(ncol = n_scorers_A + n_scorers_K, nrow = nrow(cmpt_F))), c(scorers_A, scorers_K))
rownames(cmpt_F_tmp) <- rownames(cmpt_F)

cmpt_F_tmp <- cbind(cmpt_F, cmpt_F_tmp)

cmpt_K_tmp <- setNames(data.frame(matrix(ncol = n_scorers_A + n_scorers_F, nrow = nrow(cmpt_K))), c(scorers_A, scorers_F))
rownames(cmpt_K_tmp) <- rownames(cmpt_K)

cmpt_K_tmp <- cbind(cmpt_K, cmpt_K_tmp)

cmpt <- rbind(cmpt_A_tmp, cmpt_F_tmp, cmpt_K_tmp)

# write.xlsx(cmpt, "../ti_scoring_data/cmpt.xlsx", rowNames = TRUE, keepNA = TRUE)
```

```{r include=FALSE}
ttl = apply(cmpt, 1, function(x) sum(!is.na(x)))
cmpt_c = apply(cmpt, 1, function(x) sum(x == "C", na.rm = T))
cmpt_m = apply(cmpt, 1, function(x) sum(x == "M", na.rm = T))
cmpt_cm = apply(cmpt, 1, function(x) sum(x == "C/M", na.rm = T))

cmpt_sum = data.frame(
  c = cmpt_c/ttl,
  m = cmpt_m/ttl,
  cm = cmpt_cm/ttl
)

tmp = unique(c(cmpt_sum$c, cmpt_sum$m, cmpt_sum$cm))
tmp_names = c("5/5, 4/4, 3/3", "4/5", "2/3", "1/3", "3/4", "2/4", "1/4", "0/5, 0/4, 0/3", "1/5")

cmpt_sum_tb = data.frame(
  c = c(sum(cmpt_sum$c == tmp[1], na.rm = T), sum(cmpt_sum$c == tmp[2], na.rm = T), sum(cmpt_sum$c == tmp[3], na.rm = T), 
        sum(cmpt_sum$c == tmp[4], na.rm = T), sum(cmpt_sum$c == tmp[5], na.rm = T), sum(cmpt_sum$c == tmp[6], na.rm = T), 
        sum(cmpt_sum$c == tmp[7], na.rm = T), sum(cmpt_sum$c == tmp[8], na.rm = T), sum(cmpt_sum$c == tmp[9], na.rm = T)),
  m = c(sum(cmpt_sum$m == tmp[1], na.rm = T), sum(cmpt_sum$m == tmp[2], na.rm = T), sum(cmpt_sum$m == tmp[3], na.rm = T), 
        sum(cmpt_sum$m == tmp[4], na.rm = T), sum(cmpt_sum$m == tmp[5], na.rm = T), sum(cmpt_sum$m == tmp[6], na.rm = T), 
        sum(cmpt_sum$m == tmp[7], na.rm = T), sum(cmpt_sum$m == tmp[8], na.rm = T), sum(cmpt_sum$m == tmp[9], na.rm = T)),
  cm = c(sum(cmpt_sum$cm == tmp[1], na.rm = T), sum(cmpt_sum$cm == tmp[2], na.rm = T), sum(cmpt_sum$cm == tmp[3], na.rm = T), 
        sum(cmpt_sum$cm == tmp[4], na.rm = T), sum(cmpt_sum$cm == tmp[5], na.rm = T), sum(cmpt_sum$cm == tmp[6], na.rm = T), 
        sum(cmpt_sum$cm == tmp[7], na.rm = T), sum(cmpt_sum$cm == tmp[8], na.rm = T), sum(cmpt_sum$cm == tmp[9], na.rm = T))
)

rownames(cmpt_sum_tb) = tmp_names
cmpt_sum_tb = cmpt_sum_tb[order(tmp, decreasing = TRUE),]
colnames(cmpt_sum_tb) = c("C", "M", "C/M")

cmpt_sum_tb["Total",] <- c(colSums(cmpt_sum_tb))

kbl(cmpt_sum_tb, booktabs=T, align="c", caption = "Number of grid squares that had perfect agreement or some disagreements across graders", linesep = "") %>%
  kable_styling(latex_options = c("HOLD_position")) %>%
  row_spec(nrow(cmpt_sum_tb), bold = T)
```

